### ISSUE TITLE
Strange drop in graph at (random) time?

### ISSUE THREAD

**Issue by snowienator** [snowienator/Home-Assistant-Prijsplafond#7]
Pluim003 reported the following graph:

![image](https://user-images.githubusercontent.com/688313/214240892-25dec971-d095-4d2a-b468-d554b4966298.png)

The questions to answer:
- What is causing this drop?
- Is the drop occuring at the same time every day?

My data shows the following:

![image](https://user-images.githubusercontent.com/688313/214241067-dc41957e-7536-4851-aad8-9c597de140ec.png)
With no drop..

**Comment by pluim003** [comment]
Before, the drop happened at 3AM during the restart of HomeAssistant during backup. Last night nothing was going on. Well every 4 hours a backup with open files is being made. I hadn't seen this before at 4AM though.

The corresponding sensors to be used show no dips:

![afbeelding](https://user-images.githubusercontent.com/67138922/214260480-25014a9d-e8b9-4b6f-b989-243875381267.png)

![afbeelding](https://user-images.githubusercontent.com/67138922/214260532-23109f31-7581-4d35-9561-58cfd44304d9.png)

![afbeelding](https://user-images.githubusercontent.com/67138922/214260581-a3d5d86a-4a14-4203-b76f-739d34e283dc.png)

![afbeelding](https://user-images.githubusercontent.com/67138922/214260638-fdedf878-1149-4960-b103-fe81358a6579.png)

**Comment by pluim003** [comment]
Same happened again last night around 4AM. It's very strange.

**Comment by snowienator** [comment]
I'm in the progress of adding debug markers to the sensor. After this we can check what is causing the drop.

**Comment by snowienator** [comment]
@pluim003 In release V1.0.6 I've added debug support. You can check the readme on how to enable and output the data. Can you afterwards send me the output via pastebin or so? Preferably only for this integration 😅. I'm specifically interested in like 15 minutes before the 'lets say planned drop' and 15 minutes after.

**Comment by pluim003** [comment]
Installed it and put debug logging on.

**Comment by pluim003** [comment]
Debugging doesn't show much information:

```
bash-5.1# grep plafond home-assistant.log
2023-01-27 07:37:26.291 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration prijsplafond which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-27 07:37:39.276 ERROR (MainThread) [custom_components.prijsplafond.const.const] This platform is not available to configure from 'sensor:' in configuration.yaml
2023-01-27 07:37:59.655 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}")
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}' but no default was specified
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}' but no default was specified
2023-01-27 07:37:59.664 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}' but no default was specified') while processing template 'Template("{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}")' for attribute '_attr_native_value' in entity 'sensor.prijsplafond_remaining_gas'
2023-01-27 07:37:59.670 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}")
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}' but no default was specified
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}' but no default was specified
2023-01-27 07:37:59.674 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}' but no default was specified') while processing template 'Template("{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}")' for attribute '_attr_native_value' in entity 'sensor.prijsplafond_remaining_power'
2023-01-27 14:02:01.121 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prijsplafond_power fails
  File "/config/custom_components/prijsplafond/sensor.py", line 167, in async_update
  File "/config/custom_components/prijsplafond/sensor.py", line 194, in _get_value
2023-01-27 14:02:01.129 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prijsplafond_gas fails
  File "/config/custom_components/prijsplafond/sensor.py", line 167, in async_update
  File "/config/custom_components/prijsplafond/sensor.py", line 194, in _get_value
```

It complains about the template-sensors but they work nicely so far. And there is an error at 2PM yesterday, but the drop occured again last night between 4:10 and 4:15

And further some errormessages with respect to localtuya that it can't reach one of the devices and that an update-job fails (but that happens every 5 minutes).

I am running HA in a Docker container version 2023.1.1 . Now in the progress of upgrading and a bit later: it has been upgraded to 2023.1.7.

**Comment by snowienator** [comment]
Did you also enable the debug logging on the integrations page > Prijsplafond > 3 vertical dots > enable debug logging:

![image](https://user-images.githubusercontent.com/688313/215253496-c090411c-9bb2-4bd5-91cd-5561a21e2be6.png)

I forgot to mension this in the readme 🥲

**Comment by pluim003** [comment]
I did yesterday, and I know it was active, but upon checking today I noticed it wasn't. :-(
So let's wait another day.

**Comment by pluim003** [comment]
Unfortunately no extra logging somewhere, or I must overlook it. In home-assistant.log no logging with respect to prijsplafond except the one already mentioned yesterday.

**Comment by snowienator** [comment]
Hmm.. I just enabled mine to test it.. And I immediately get the lines I need.. 

2023-01-29 11:24:37.054 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Async setup Prijsplafond
2023-01-29 11:24:37.054 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] Positive entities: ['sensor.zonneplan_test_meter']
2023-01-29 11:24:37.054 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] Negative entities: []
2023-01-29 11:24:37.054 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] Positive entities: ['sensor.p1_meter_5c2faf0544ee_total_gas']
2023-01-29 11:24:37.054 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] Negative entities: []

I found these in home-assistant_2023-01-29T10-26-53.854Z.log

**Comment by snowienator** [comment]
@pluim003 you sure you have configured the logger in your yaml and enabled debugging logging in the integration?

**Comment by pluim003** [comment]
Checked this morning in the integration and it was still put to debug and these are the contents of logger.yaml:

```
    # log level for a custom component
    custom_components.localtuya: error
    custom_components.prijsplafond: debug
```

**Comment by pluim003** [comment]
After my message yesterday I restarted the whole HomeAssistant. Now log shows a bit more:

```
bash-5.1# grep prijsplafond home-assistant.log
2023-01-29 16:19:54.767 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration prijsplafond which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-29 16:20:07.533 ERROR (MainThread) [custom_components.prijsplafond.const.const] This platform is not available to configure from 'sensor:' in configuration.yaml
2023-01-29 16:20:27.351 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}")
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}' but no default was specified
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}' but no default was specified
2023-01-29 16:20:27.382 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}' but no default was specified') while processing template 'Template("{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_gas') | float | round(2) ) }}")' for attribute '_attr_native_value' in entity 'sensor.prijsplafond_remaining_gas'
2023-01-29 16:20:27.413 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}")
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}' but no default was specified
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}' but no default was specified
2023-01-29 16:20:27.417 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}' but no default was specified') while processing template 'Template("{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) - (states('sensor.prijsplafond_power') | float | round(2) ) }}")' for attribute '_attr_native_value' in entity 'sensor.prijsplafond_remaining_power'
2023-01-30 04:13:02.337 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prijsplafond_power fails
  File "/config/custom_components/prijsplafond/sensor.py", line 172, in async_update
  File "/config/custom_components/prijsplafond/sensor.py", line 186, in _get_value
2023-01-30 04:14:02.331 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prijsplafond_power fails
  File "/config/custom_components/prijsplafond/sensor.py", line 172, in async_update
  File "/config/custom_components/prijsplafond/sensor.py", line 186, in _get_value
2023-01-30 04:15:02.372 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prijsplafond_power fails
  File "/config/custom_components/prijsplafond/sensor.py", line 172, in async_update
  File "/config/custom_components/prijsplafond/sensor.py", line 186, in _get_value
2023-01-30 04:16:02.334 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prijsplafond_power fails
  File "/config/custom_components/prijsplafond/sensor.py", line 172, in async_update
  File "/config/custom_components/prijsplafond/sensor.py", line 186, in _get_value
```
and that keeps going on and on. But it starts at 4:13. That's odd. But the drop also occurs at 4:15.

More detail at the first occurence:

```
2023-01-30 04:13:02.337 ERROR (MainThread) [homeassistant.helpers.entity] Update
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in as
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in as
    raise exc
  File "/config/custom_components/prijsplafond/sensor.py", line 172, in async_up
    neg_usage += await self._get_value(entity_id)
  File "/config/custom_components/prijsplafond/sensor.py", line 186, in _get_val
    usage = float(state_old.state)
ValueError: could not convert string to float: 'unavailable'
```

**Comment by pluim003** [comment]
Another weird thing: this night the drop only in gas, but electricity no drop, but unknown:

![afbeelding](https://user-images.githubusercontent.com/67138922/215403992-f7b4f79f-5717-46e3-9d28-43835b19c69e.png)

and the mentioned errors continue every minute., even after a restart when I wanted to get rid of the localtuya-errormessaages.

**Comment by snowienator** [comment]
> 

@pluim003, please update to latest release.

**Comment by snowienator** [comment]
ValueError: could not convert string to float: 'unavailable'

In your log.. This is odd.. Do you have changed anything for you history or database?

**Comment by pluim003** [comment]
Nope, didn't change anything and at 4AM I'm sound asleep. Stuff is also exported to an InfluxDB.

With respect to updating: I removed it and will reinstall. Also noticed that when I wanted to remove it debug logging was off, which I haven't done.

**Comment by pluim003** [comment]
After reinstall I see this (same as just before):

![afbeelding](https://user-images.githubusercontent.com/67138922/215416604-b97d027d-6b4d-46f6-ae09-8ad6507459a5.png)

And in the log:

```2023-01-30 08:41:45.542 ERROR (MainThread) [homeassistant.helpers.entity] Update for
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_
    raise exc
  File "/config/custom_components/prijsplafond/sensor.py", line 172, in async_update
    neg_usage += await self._get_value(entity_id)
  File "/config/custom_components/prijsplafond/sensor.py", line 186, in _get_value
    usage = float(state_old.state)
ValueError: could not convert string to float: 'unavailable'
````

**Comment by pluim003** [comment]
Noticed the latter issue is mentioned in https://github.com/rbrink/Home-Assistant-Prijsplafond/issues/9 .

With respect to that, these are the ones I use:

![afbeelding](https://user-images.githubusercontent.com/67138922/215417784-cef84b55-1dc1-4cf8-a75d-743dad0e074e.png)

**Comment by pluim003** [comment]
I was thinking: as it is now being installed through the regular interface the debug logging should be modified to not use the custom_component. In that folder there are still the 'old' files dating back from Jan 23rd.

Downloaded release 1.0.7 and extracted it over the existing installation in custom_components. Now some more logging is showing up.

**Comment by snowienator** [comment]
Hmm.. When I install an integration through HACS it stores them in the configuration/custom_components folder. Where does your version store them?

**Comment by pluim003** [comment]
Through HACS it didn't work. I manually installed it in /config/custom_components (Dockercontainer). I also notice indeed the /config/configuration/custom_components-folder but that has older stuff. I guess a backup.

First debug logging:

```2023-01-30 11:54:01.993 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting first recorded state of this month for: sensor.p1_meter_total_power_import_t1 resulted in: 7663.996
2023-01-30 11:54:01.993 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_power_import_t1 resulted in: 7707.726
2023-01-30 11:54:02.001 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting first recorded state of this month for: sensor.p1_meter_total_power_import_t2 resulted in: 7229.726
2023-01-30 11:54:02.001 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_power_import_t2 resulted in: 7271.26
2023-01-30 11:54:02.001 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] In update pos_usage is 85.26400000000012
2023-01-30 11:54:02.007 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting first recorded state of this month for: sensor.p1_meter_total_gas resulted in: 8923.593
2023-01-30 11:54:02.007 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_gas resulted in: 9004.597
2023-01-30 11:54:02.007 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] In update pos_usage is 81.003999999999
2023-01-30 11:54:02.007 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] In update neg_usage is 0
2023-01-30 11:54:02.007 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] In update total_usage is 81.003999999999
2023-01-30 11:54:02.018 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting first recorded state of this month for: sensor.p1_meter_total_power_export_t1 resulted in: 3238.097
2023-01-30 11:54:02.018 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_power_export_t1 resulted in: 3238.286
2023-01-30 11:54:02.026 WARNING (MainThread) [custom_components.prijsplafond.const.const] Unable to convert the first recorded state of this month for: sensor.p1_meter_total_power_export_t2 to float..Value is: unavailable. Setting usage to 0.
2023-01-30 11:54:02.028 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_power_export_t2 resulted in: 7229.332
2023-01-30 11:54:02.028 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] In update neg_usage is 7229.521000000001
2023-01-30 11:54:02.028 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] In update total_usage is -7144.2570000000005
2023-01-30 11:55:14.485 ERROR (MainThread) [frontend.js.latest.202301100] :0:0 ResizeObserver loop completed with undelivered notifications.

```

Guess I'll remove the export-entities in the integration and see what happens. Not much to export during these months.

Update: did that but probably needed to restart HA as it still was complaining about the export_t2:

```
2023-01-30 12:06:09.861 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting first recorded state of this month for: sensor.p1_meter_total_power_import_t1 resulted in: 7663.996
2023-01-30 12:06:09.862 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_power_import_t1 resulted in: 7707.726
2023-01-30 12:06:09.871 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting first recorded state of this month for: sensor.p1_meter_total_gas resulted in: 8923.593
2023-01-30 12:06:09.871 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_gas resulted in: 9005.066
2023-01-30 12:06:09.872 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] In update pos_usage is 81.47299999999996
2023-01-30 12:06:09.872 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] In update neg_usage is 0
2023-01-30 12:06:09.872 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_gas] In update total_usage is 81.47299999999996
2023-01-30 12:06:09.872 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting first recorded state of this month for: sensor.p1_meter_total_power_import_t2 resulted in: 7229.726
2023-01-30 12:06:09.872 DEBUG (MainThread) [custom_components.prijsplafond.const.const] Getting current state for sensor.p1_meter_total_power_import_t2 resulted in: 7271.305
2023-01-30 12:06:09.873 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] In update pos_usage is 85.3090000000002
2023-01-30 12:06:09.873 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] In update neg_usage is 0
2023-01-30 12:06:09.873 DEBUG (MainThread) [custom_components.prijsplafond.const.const] [sensor.prijsplafond_power] In update total_usage is 85.3090000000002
```

I'm curious what will happen this night with respect to the first value of the month, as that wouldn't be correct. As currently gas usage is 189 m3 for this month, unless that is being recorded wrongly.

And according to enelogic.com the total usage of gas was until Saturday 182 m3. Could it be that during the night the first recorded value of the month get off, but then why and how?

And than a bit later: I wanted to look at the history of the P1-meter for Gas and choose Jan 1st until now to find out that it only shows Jan 21st until now... So in one way or another there is a cleanup of tjhis data. Now to figure out where that is being done.

**Comment by pluim003** [comment]
So added purge_keep_days: 91 to recorder.yaml. See if this will solve thie issues.

**Comment by daantjuuh1992** [comment]
I think this purge_keep_days could be the problem. The last 15 days of energy usage is about the amount the sensor prijsplafond shows me. I changed purge_keep_days to 90 to test.

**Comment by Alfagek** [comment]
Also here a drop in power on 00:00 last night. And also a drop in the gas.
And the error in the log.
Installed it since yesterday.

Example of the Gas sensor:
![image](https://user-images.githubusercontent.com/76258622/215487572-97315801-3b9a-41cc-a340-fe9d061225fb.png)

**Comment by pluim003** [comment]
That's the same issue I had. It must be between 4 and 4:15 (according to your graph it might also be that). Seems that data is being purged, so the solution is above and hopefully it works now.
I also export to an InfluxDB and there was the data of the sensors being used still present (retention of 90 days).

**Comment by Alfagek** [comment]
@pluim003 
Gas is around 4:10-4:15 and the power is between 00:00 and 00:05

So thats a diffrent time :-(

**Comment by snowienator** [comment]
Never thought of the retention option😅, I usually store all data for a long time.

Now I do wonder if the purging is a rolling proces as they have different times. Do other entities behave the same but at another moment?

**Comment by pluim003** [comment]
> @pluim003 Gas is around 4:10-4:15 and the power is between 00:00 and 00:05
> 
> So thats a diffrent time :-(

Hmm... dunno what it triggers. Mine are both between 4:10-4:15. Odd.

**Comment by pluim003** [comment]
> Never thought of the retention option😅, I usually store all data for a long time.
> 
> Now I do wonder if the purging is a rolling proces as they have different times. Do other entities behave the same but at another moment?

Dunno. I never set it up actually. Well, data is also being transferred to InfluxDB where I use it for Grafana-dashboards. I wasn't totally are of this cleanup, which defaults to 10 days as I read. Dunno how it's being done for the energy dashboard as that shows correct data.
But fortunately we figured it out. Tomorrow morning if I have done everything correctly, I shouldn't see a drop.
But at least it's not an issue/bug in your integration.

**Comment by snowienator** [comment]
True, but it's still good we have (we might) figured it out.. I do have a thing to set for discussion.

Now when the 'first month value' is not available I convert it to 0, but actually it doesnt make any sense. What are you thoughts on about showing an error instead of warning? And then I can actually stop the integration as it has no use when there is no imput data

**Comment by pluim003** [comment]
I would say, if that happens on the 1st of the month it's totally fine to start with 0. If it's at another day of the month I would indeed suggest that there is no input, or wrong input which can cause the integration not to be accurate and data gathered might not be reliable.

**Comment by Alfagek** [comment]
The time difference between the energy and gas would suggest me, that it isn’t the purge. I do also have a few custom sensor for month and day and there i don’t see any drop or spike. So that’s the strange thing. That’s why i think it’s something else that causing this problem. But what …………..

**Comment by pluim003** [comment]
Update: with recorder modified the drop didn't occur this night.

**Comment by dickwolff** [comment]
I have also changed the recorder, gas graph looks to be okay, power seems off though. 

![Screenshot_2023-01-31-07-54-38-10_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/5620002/215688190-97c89393-0af8-432d-962c-11eacee61a34.jpg)

**Comment by pluim003** [comment]
@dickwolff  Do you have solar panels? If so it might be the return to the net causing the slight drop during the day. In my case however I don't see this drop which I would expect, especially during hours when I return more than receive from the net, f.e. the last hour:

![afbeelding](https://user-images.githubusercontent.com/67138922/221539497-caa2237c-399f-4212-b440-885584a14264.png)

![afbeelding](https://user-images.githubusercontent.com/67138922/221539610-67eb7f44-ef83-4b46-ab01-33e4271e6091.png)

**Comment by dickwolff** [comment]
@pluim003 I do have solar panels, yes. But what seemed more off was the increase on the transition between jan. 30 and 31. 
![image](https://user-images.githubusercontent.com/5620002/221540618-f36969fd-dc37-43bc-a3d0-62fa2bff2a14.png)

**Comment by pluim003** [comment]
That's indeed an odd one unless you were cooking on induction in the middle of the night. :-)

**Comment by pluim003** [comment]
Just want to say that when I looked at the used power this month (especially today) it is dropping when more is returned to the net than being 'taken'.

**Comment by snowienator** [comment]
Last message from me in this repo as it is no longer needed due to the fact the price regulation thingy stopped. Thanks for all support!
